// This file will be auto-generated by Convex when you run `bunx convex dev`
// For now, this is a placeholder to satisfy TypeScript

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const api = {} as any;
